# Generated by Django 4.0.2 on 2022-03-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_elgibility_scheme_eligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Scholarship', models.BooleanField()),
                ('Social', models.BooleanField()),
            ],
        ),
    ]
