# Generated by Django 4.0.2 on 2022-03-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mailform'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailform',
            name='Employment',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
