# Generated by Django 3.2.12 on 2022-04-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_schemescholarships'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemescholarships',
            options={'verbose_name': 'Scheme - Scholarship', 'verbose_name_plural': 'Scheme - Scholarships'},
        ),
        migrations.AddField(
            model_name='mailform',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailform',
            name='OTP',
            field=models.CharField(default=111111, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailform',
            name='Tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mailform',
            name='Employment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mailform',
            name='Name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='mailform',
            name='Scholarship',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mailform',
            name='Social',
            field=models.BooleanField(default=False),
        ),
    ]
