# Generated by Django 3.2.12 on 2022-04-02 06:10

from django.db import migrations, models
import uuid

def create_uuid(apps, schema_editor):
    MailForm = apps.get_model('main', 'MailForm')
    for mailform in MailForm.objects.all():
        mailform.UUID = uuid.uuid4()
        mailform.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_mailform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailform',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='mailform',
            name='UUID',
            field=models.UUIDField(unique=True, editable=False, blank=False, null=False)
        )
    ]
