# Generated by Django 3.2.12 on 2022-05-08 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mailform_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=10000)),
                ('hi', models.CharField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
            },
        ),
        migrations.AlterField(
            model_name='mailform',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
